
package az.unibank.stream.implementation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "STREAM", targetNamespace = "STREAM", wsdlLocation = "file:/C:/Users/azarm/Documents/NetBeansProjects/Stream/GoldenPayProxyCurrentVersion/src/conf/xml-resources/web-service-references/WsClient/wsdl/public.api.stream.unibank.lan_5443/.wsdl")
public class STREAM
    extends Service
{

    private final static URL STREAM_WSDL_LOCATION;
    private final static WebServiceException STREAM_EXCEPTION;
    private final static QName STREAM_QNAME = new QName("STREAM", "STREAM");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/azarm/Documents/NetBeansProjects/Stream/GoldenPayProxyCurrentVersion/src/conf/xml-resources/web-service-references/WsClient/wsdl/public.api.stream.unibank.lan_5443/.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STREAM_WSDL_LOCATION = url;
        STREAM_EXCEPTION = e;
    }

    public STREAM() {
        super(__getWsdlLocation(), STREAM_QNAME);
    }

    public STREAM(WebServiceFeature... features) {
        super(__getWsdlLocation(), STREAM_QNAME, features);
    }

    public STREAM(URL wsdlLocation) {
        super(wsdlLocation, STREAM_QNAME);
    }

    public STREAM(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STREAM_QNAME, features);
    }

    public STREAM(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public STREAM(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns STREAMPort
     */
    @WebEndpoint(name = "STREAMPort")
    public STREAMPort getSTREAMPort() {
        return super.getPort(new QName("STREAM", "STREAMPort"), STREAMPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns STREAMPort
     */
    @WebEndpoint(name = "STREAMPort")
    public STREAMPort getSTREAMPort(WebServiceFeature... features) {
        return super.getPort(new QName("STREAM", "STREAMPort"), STREAMPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STREAM_EXCEPTION!= null) {
            throw STREAM_EXCEPTION;
        }
        return STREAM_WSDL_LOCATION;
    }

}
